### ISSUE TITLE
[service-deployment] Redis Service CCE 이슈

### ISSUE THREAD

**Issue by okpc579** [PaaS-TA/service-deployment#12]
CCE 이슈 목록
|종류|호스트명|CCE-ID|점검항목|
|------|---|---|--|
|Linux|mariadb|U-07|파일 및 디렉터리 소유자 설정|
|Linux|mariadb|U-07|world writable 파일 점검|
|MySQL|mariadb|DY-07|안전한 암호화 알고리즘 사용|
|MySQL|mariadb|DY-08|로그 활성화|
|MySQL|mariadb|DY-09|최신 패치 적용|
|Redis|redis|DR-01|Redis 인증 패스워드 설정|
|Redis|redis|DR-02|Binding 설정|
|Redis|redis|DR-04|rename-command 설정|
|Redis|redis|DR-06|설정파일 접근권한 설정|
|Redis|redis|DR-08|최신 패치 적용|

**Comment by moonii** [comment]
[ [ enable CCE ]  https://github.com/PaaS-TA/PAAS-TA-ON-DEMAND-REDIS-RELEASE/pull/2](https://github.com/PaaS-TA/PAAS-TA-ON-DEMAND-REDIS-RELEASE/pull/2)
