### ISSUE TITLE
[service-deployment] MongoDB Service CCE 이슈

### ISSUE THREAD

**Issue by okpc579** [PaaS-TA/service-deployment#14]
CCE 이슈 목록
|종류|호스트명|CCE-ID|점검항목|
|------|---|---|--|
|MongoDB|mongodb_config|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_master1|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_master2|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_master3|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_shard|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_slave1|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_slave2|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_slave3|MG-01|불필요한 데이터베이스 및 테이블 제거|
|MongoDB|mongodb_config|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_master1|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_master2|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_master3|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_shard|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_slave1|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_slave2|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_slave3|MG-05|주요 실행 및 설정 파일 권한 관리|
|MongoDB|mongodb_config|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|
|MongoDB|mongodb_master1|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|
|MongoDB|mongodb_master2|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|
|MongoDB|mongodb_master3|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|
|MongoDB|mongodb_shard|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|
|MongoDB|mongodb_slave1|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|
|MongoDB|mongodb_slave2|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|
|MongoDB|mongodb_slave3|MG-08|데이터베이스에 대해 최신 보안패치와 벤더 권고사항 적용|

**Comment by jinhyojin** [comment]
https://github.com/PaaS-TA/PAAS-TA-MONGODB-SHARD-RELEASE/pull/1

**Comment by jinhyojin** [comment]
[ [ enable CCE ]  https://github.com/PaaS-TA/PAAS-TA-MONGODB-SHARD-RELEASE/pull/1](https://github.com/PaaS-TA/PAAS-TA-MONGODB-SHARD-RELEASE/pull/1)
