### ISSUE TITLE
[service-deployment] Lifecycle-Service CCE 이슈

### ISSUE THREAD

**Issue by okpc579** [PaaS-TA/service-deployment#6]
CCE 이슈 목록
|종류|호스트명|CCE-ID|점검항목|
|------|---|---|--|
|Nginx|app-lifecycle|NG-07|안정화 버전 및 패치 적용|
|MySQL|mariadb|DY-07|안전한 암호화 알고리즘 사용|
|MySQL|mariadb|DY-08|로그 활성화|
|MySQL|mariadb|DY-09|최신 패치 적용|
|PostgreSQL|app-lifecycle|DP-02|취약한 패스워드 사용 제한|
|PostgreSQL|app-lifecycle|DP-04|public schema 사용 제한|
|PostgreSQL|app-lifecycle|DP-06|안전한 인증 방식 설정|
|PostgreSQL|app-lifecycle|DP-07|안전한 암호화 알고리즘 사용|
|PostgreSQL|app-lifecycle|DP-09|환경 설정파일 권한 설정|
|PostgreSQL|app-lifecycle|DP-10|로그 활성화|

**Comment by moonii** [comment]
[https://github.com/PaaS-TA/PAAS-TA-APP-LIFECYCLE-SERVICE-BROKER/pull/1](https://github.com/PaaS-TA/PAAS-TA-APP-LIFECYCLE-SERVICE-BROKER/pull/1)
