### ISSUE TITLE
[service-deployment] MySQL Service CCE 이슈

### ISSUE THREAD

**Issue by okpc579** [PaaS-TA/service-deployment#9]
CCE 이슈 목록
|종류|호스트명|CCE-ID|점검항목|
|------|---|---|--|
|Linux|mysql|U-23|DoS 공격에 취약한 서비스 비활성화|
|MySQL|mysql|DY-07|안전한 암호화 알고리즘 사용|
|MySQL|mysql|DY-08|로그 활성화|
|MySQL|mysql|DY-09|최신 패치 적용|

**Comment by jinhyojin** [comment]
[ [ enable CCE ]  https://github.com/PaaS-TA/PAAS-TA-MYSQL-RELEASE/pull/12](https://github.com/PaaS-TA/PAAS-TA-MYSQL-RELEASE/pull/12)
[ [ enable CCE ]  https://github.com/PaaS-TA/OPENPAAS-SERVICE-JAVA-BROKER-MYSQL/pull/1](https://github.com/PaaS-TA/OPENPAAS-SERVICE-JAVA-BROKER-MYSQL/pull/1)
